version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.2
    container_name: kibana
    ports:
      - "5601:5601"

  logstash:
    image: docker.elastic.co/logstash/logstash:7.15.2
    container_name: logstash
    volumes:
      - /Users/akrurneupane/Documents/DevOps/Projects/treeleaf/treeleaf/logstash:/usr/share/logstash/config
   
    command: logstash -f /usr/share/logstash/config/logstash.conf

    ports:
      - "5001:5001"
    depends_on:
      - elasticsearch
