apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: javaapp
  template:
    metadata:
      labels:
        app: javaapp
    spec:
      containers:
      - name: javaapp
        image: neupaneakrur/javaapp
        ports:
        - containerPort: 8080
